# Tarea pytorch, parte A

Recuerda que no se vale utilizar la palabra `for`.

1. Encuentra la derivada de $x^2 + 2x + 5$ evaluada en $x = 1$ (con pytorch).
2. ¿Para qué sirve squeeze y unsqueeze? ¿Qué recomiendo usar en vez de unsqueeze? 
3. Si tengo una matriz `A` de $8\times 10$, ¿de qué tamaño será `A[1:6,-2:]`?
4. Súmale 10 al primer renglón y 20 al segundo renglón. Escribe poquito.
5. Crea una matriz de $n\times m$ donde en la entrada $(i,j)$ esté el número $i+j$. No se vale usar la palabra `for`. Con `arange` e indizar.
6. Dado dos tensores lineales de tamaño $n\times 2$ y $m \times 2$ respectivamente, crea una matriz de $n\times m$ en donde la entrada $(i,j)$ sea la distancia euclideana entre el punto $i$ del primero tensor y el punto $j$ del segundo tensor. Igual, la palabra `for` está prohibida.
7. Dado una matriz $A$ de $n\times m$ y un vector de enteros $b$ donde todos los números de $b$ van del 0 a m, selecciona los números en las columnas correspondientes a $b$ y ponlos como $-1$. Por ejemplo, si 

$$A = \begin{bmatrix}
        0 & 1 & 2 & 3 \\
        4 & 5 & 6 & 7 \\
      \end{bmatrix}$$
y $b = [2, 0]$, entonces debe resultar en:

$$A = \begin{bmatrix}
        0 & 1 & -1 & 3 \\
        -1 & 5 & 6 & 7 \\
      \end{bmatrix}$$
      
8. (**difícil**) Implementa, sin usar `@` ni matmul, multiplicación de matrices. Se vale usar `*`, `+`, `sum` y broadcasting.

In [1]:
import torch
import fastai

In [2]:
torch.cuda.is_available()

False

# 1. Encuentra la derivada de x2+2x+5 evaluada en x=1 (con pytorch).
> **R: 4**


In [3]:
def derivate(x,y):
  """
  x = Tensor to evaluate (the point on X)
  y = your function 
  """
  y.backward() #backward guarda nuestros gradientes en hojas
  result = x.grad #grad recupera los gradientes en hojas, los suma usando la regla de la cadena  y arroja el resultado
  return(result)

#x = torch([[1.]],requires_grad=True)
#Autograd nos proporciona funciones para hacer las diferenciales de manera automatica
#Para hacer uso de ello introducimos True para el parámetro requires_grad
#NOTA: debe de ser un tensor escalar (Ya que la salida tras evaluar es un único número)de punto flotante 
#ya que no hay soporte para otros
x = torch.tensor([1.], requires_grad=True) 
y = x**2 + 2*x + 5 # Escribimos nuestra función

#y.backward() #backward guarda nuestros gradientes en hojas
#x.grad #grad recupera los gradientes en hojas, los suma usando la regla de la cadena  y arroja el resultadod
derivate(x, y)

tensor([4.])

# 2. ¿Para qué sirve squeeze y unsqueeze? 
###squeeze: Quita todas las dimensiones de valor 1
> Si tenemos: torch.tensor([1, 3, 1, 1, 4, 5]) y aplicamos squeeze
> Ahora tendremos torch.tensor([3, 4, 5])
###unsqueeze: Hace lo contrario a squeeze, te añade dimensión 1 
> si tenemos: torch.tensor([3,4,5]) y aplicamos unsqueeze(1) 
> Ahora tendremos torch.tensor([3,1,4,5]), añade la dimensión en 
el lugar que le pasas como parámetro, comenzando desde cero
# 2.1. ¿Qué recomiendo usar en vez de unsqueeze?
> Usar la palabra reservada **None**, ya que combinado con las listas,
puede hacer lo mismo que unsqueeze pero es un poco más rápido.
Sí tenemos torch.tensor([1,3,1,1,4,5]) su dimensión es [6] = x.shape
pero si queremos añadir una más, basta con hacer x[:,None] = [6,1] = x.shape


In [4]:
x = torch.zeros(2, 1, 2, 1, 2, 3, 5, 1)
#y = torch.squeeze(x, 0) # Si pasamos el indice cero, el tensor se queda igual
#y = torch.squeeze(x, 1) # Si paso como indice el uno, sólo se elimina un uno del tensor, no entiendo muy bien la razón. 
# Crei que si copiaba la misma línea una segunda vez, se eliminaria el segundo uno pero no fue así.
x.shape

torch.Size([2, 1, 2, 1, 2, 3, 5, 1])

In [5]:
y = torch.squeeze(x) # Si no paso nada, se comprime tal como lo dice la documentación, se comprimen todos los valores 1's 
y.shape

torch.Size([2, 2, 2, 3, 5])

In [6]:
x = torch.tensor([1, 2, 3, 4,5,6,7,8,9,11,1])
#torch.unsqueeze(x, 0) # Si pasamos como indice el valor cero, deja el tensor como esta
x.shape

torch.Size([11])

In [7]:
y = torch.unsqueeze(x, 1); y.shape

torch.Size([11, 1])

In [8]:
y[:,:,None].shape

torch.Size([11, 1, 1])

In [9]:
x = torch.tensor([1, 3, 1, 1, 4, 5]); x.shape

torch.Size([6])

In [10]:
x[:].shape

torch.Size([6])

In [11]:
x[:,None].shape

torch.Size([6, 1])

# 3. Si tengo una matriz `A` de $8\times 10$, ¿de qué tamaño será `A[1:6,-2:]`?
**R: 5 filas y 2 columnas, dado que toma la fila uno hasta la 5,
ya que no incluye al 6, y columnas -2: significa que tomara las dos primeras comenzando desde el final hasta el inicio.**


In [12]:
A = torch.rand(8,10);
A.shape
# Alto, Ancho, Profundo
# Números aleatorios entre cero y uno [0, 1]
# Distribuidos uniformemente

torch.Size([8, 10])

In [13]:
 A[1:6,-2:].shape # Toma la fila uno hasta la 5, no incluye 6, y toma las dos últimas columnas

torch.Size([5, 2])

In [14]:
A

tensor([[0.9768, 0.6018, 0.9144, 0.0079, 0.6518, 0.5264, 0.9401, 0.2835, 0.6769,
         0.9508],
        [0.9443, 0.6794, 0.5771, 0.8815, 0.8549, 0.6018, 0.5081, 0.0702, 0.8621,
         0.1491],
        [0.4326, 0.3925, 0.4982, 0.0288, 0.1652, 0.6724, 0.4187, 0.6820, 0.9770,
         0.2109],
        [0.1780, 0.1360, 0.9867, 0.9970, 0.2858, 0.7942, 0.8048, 0.3913, 0.8990,
         0.2160],
        [0.6545, 0.1152, 0.2985, 0.1026, 0.5033, 0.4175, 0.8402, 0.9477, 0.3787,
         0.5549],
        [0.3857, 0.8621, 0.5115, 0.9454, 0.4239, 0.1973, 0.1146, 0.5811, 0.2549,
         0.6971],
        [0.4262, 0.0844, 0.9593, 0.1174, 0.8946, 0.4388, 0.0216, 0.2426, 0.8292,
         0.5528],
        [0.1541, 0.4336, 0.2459, 0.5148, 0.9363, 0.5342, 0.6586, 0.2000, 0.7652,
         0.6066]])

In [15]:
A = A[1:6,-2:]; A

tensor([[0.8621, 0.1491],
        [0.9770, 0.2109],
        [0.8990, 0.2160],
        [0.3787, 0.5549],
        [0.2549, 0.6971]])

# 4. Súmale 10 al primer renglón y 20 al segundo renglón. Escribe poquito.

In [16]:
A

tensor([[0.8621, 0.1491],
        [0.9770, 0.2109],
        [0.8990, 0.2160],
        [0.3787, 0.5549],
        [0.2549, 0.6971]])

In [17]:
A[0] +=10; A[1] += 20; A # No sabíía si el 4 se referia a la matriz obtenida en 3 por lo que supuse que
# debia de continuar con esa matriz y es por ello que es esa matriz a la que le sume 10 a la primer
# fila y 20 a la segunda fila

tensor([[10.8621, 10.1491],
        [20.9770, 20.2109],
        [ 0.8990,  0.2160],
        [ 0.3787,  0.5549],
        [ 0.2549,  0.6971]])

# 5. Crea una matriz de $n\times m$ donde en la entrada $(i,j)$ esté el número $i+j$. No se vale usar la palabra `for`. Con `arange` e indizar.

**Este texto es una explicación del autor para si mismo, por lo que la persona que este revisando esto se lo puede saltar.**
> Únicamente me queria explicar el funcionamiento o lo que pasaba tras bambalinas con broadcasting. 
A partir de lo anterior puedo describirme y explicarme a mi mismo los 
pasos del broadcasting para llegar al resultado: 

A = [0.0253, 0.3179, 0.4786]
B = [0,1,2]
B[:,None] = [[0], [1], [2]]

A+B[:,None]=[[0.0253, 0.3179, 0.4786], [1.0253, 1.3179, 1.4786], [2.0253, 2.3179, 2.4786]]

Para llegar a ese resultado mediante broadcasting (siguiendo la explicacióón de Raggi en el vídeo) fue: 

**Alineación**

|3|1|
|-|-|
| |3|
 
Donde 3,1 es la dimensión de la matriz B[:, None] y 3 la dimensión de la matriz A.

**Igualación superior**

|3|3|
|-|-|
|1|3|

Dónde ahora la dimensión de la matriz B[:, None] es 3,3 que es igual a: 
[[0, 0, 0], [1, 1, 1], [2, 2, 2]] = B[:, None]
y la dimensión de la matriz A ahora es 1,3 que es igual a: 
[[0.0253, 0.3179, 0.4786]] = A

**Igualación inferior**

Donde la dimensióón de la matriz B[:, None] es 3,3 tal como se describio en el paso anterior pero ahora la dimensióón de la matriz A es 3,3 que es igual a: 
[[0.0253, 0.3179, 0.4786], [0.0253, 0.3179, 0.4786], [0.0253, 0.3179, 0.4786]] = A

Dado que la sumatoria de matriz es coordenada a coordenada, o sea:
[[1, 2], [3, 4]] + [[1, 2], [3, 4]] 
Uno se suma con uno, dos con dos, tres con tres y cuatro con cuatro. 

Y de esta manera es como se llega al resultado de A+B[:, None]


In [82]:
def generate_matrix(n,m):
  """
  n=filas
  m=columnas
  """
  A = torch.arange(m); B = torch.arange(n)
  #print(A, B, "\n")
  matrix = A+B[:, None]
  return (matrix)

print(generate_matrix(5,4))

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7]])


In [19]:
A = torch.arange(3)
B = torch.arange(3)
A+B[:,None], A, B

(tensor([[0, 1, 2],
         [1, 2, 3],
         [2, 3, 4]]), tensor([0, 1, 2]), tensor([0, 1, 2]))

In [20]:
AA = A+B[:,None]; AA[2,1]

tensor(3)

In [21]:
A = torch.rand(3)
B = torch.arange(3)
A.shape, B.shape, B[:,None].shape

(torch.Size([3]), torch.Size([3]), torch.Size([3, 1]))

In [22]:
A+B[:, None], B, A

(tensor([[0.9768, 0.3205, 0.5127],
         [1.9768, 1.3205, 1.5127],
         [2.9768, 2.3205, 2.5127]]),
 tensor([0, 1, 2]),
 tensor([0.9768, 0.3205, 0.5127]))

In [23]:
A, B, B[:,None]

(tensor([0.9768, 0.3205, 0.5127]), tensor([0, 1, 2]), tensor([[0],
         [1],
         [2]]))

In [24]:
A = torch.rand(1,3);A

tensor([[0.1544, 0.0937, 0.8034]])

In [25]:
A = torch.rand(3,3);A

tensor([[0.3664, 0.7774, 0.1591],
        [0.3636, 0.5845, 0.5779],
        [0.6733, 0.4907, 0.3294]])

In [26]:
A+B[:, None]

tensor([[0.3664, 0.7774, 0.1591],
        [1.3636, 1.5845, 1.5779],
        [2.6733, 2.4907, 2.3294]])

In [27]:
A = torch.rand(3,1); A

tensor([[0.2974],
        [0.3833],
        [0.9836]])

# 6. Dado dos tensores lineales de tamaño n×2 y m×2 respectivamente, crea una matriz de n×m en donde la entrada (i,j) sea la distancia euclideana entre el punto i del primero tensor y el punto j del segundo tensor. Igual, la palabra for está prohibida.

In [28]:
def euclidan_distan(n,m):
  # Creamos dos tensores de dimensiones nx2 y mx2 con valores aleatorios de entre 0 y 10 
  A = torch.randint(0,10,(m,2)); A = A.float()
  B = torch.randint(0,10,(n,2)); B = B.float()
  
  # .cdist nos devuelve la distancia euclidiana entre tensores, tomando como entrada 
  # dos tensores donde p=2 corresponde a la distancia euclidiana 
  C = torch.cdist(A, B, p=2, compute_mode='use_mm_for_euclid_dist')
  #print(A,"\n\n", B,"\n",C.shape,C.T.shape)
  #print("CCC",C, "\n")
  #matrix = A+B[:, None]
  #print(C.T)
  print(A,"\n\n", B,"\n")
  return(C.T)

euclidan_distan(3,3)

tensor([[1., 6.],
        [8., 5.],
        [5., 3.]]) 

 tensor([[3., 0.],
        [4., 8.],
        [8., 5.]]) 



tensor([[6.3246, 7.0711, 3.6056],
        [3.6056, 5.0000, 5.0990],
        [7.0711, 0.0000, 3.6056]])

In [29]:
"""n = 2; m = 3
A = torch.randint(0,10,(m,2)); A = A.float()
print("\n",A,"\n")
B = torch.randint(0,10,(n,2))
B = B.float()
print("\n",B,"\n")
C = torch.cdist(A, B, p=2, compute_mode='use_mm_for_euclid_dist')
print("C\n",C, "\n", C.shape)
matrix = A+B[:, None]
#matrix = matrix.reshape(n,m)
print(matrix, matrix.shape)"""

'n = 2; m = 3\nA = torch.randint(0,10,(m,2)); A = A.float()\nprint("\n",A,"\n")\nB = torch.randint(0,10,(n,2))\nB = B.float()\nprint("\n",B,"\n")\nC = torch.cdist(A, B, p=2, compute_mode=\'use_mm_for_euclid_dist\')\nprint("C\n",C, "\n", C.shape)\nmatrix = A+B[:, None]\n#matrix = matrix.reshape(n,m)\nprint(matrix, matrix.shape)'

In [30]:
torch.arange(2,6)

tensor([2, 3, 4, 5])

# 7. Dado una matriz $A$ de $n\times m$ y un vector de enteros $b$ donde todos los números de $b$ van del 0 a m, selecciona los números en las columnas correspondientes a $b$ y ponlos como $-1$. Por ejemplo, si 

$$A = \begin{bmatrix}
        0 & 1 & 2 & 3 \\
        4 & 5 & 6 & 7 \\
      \end{bmatrix}$$
y $b = [2, 0]$, entonces debe resultar en:

$$A = \begin{bmatrix}
        0 & 1 & -1 & 3 \\
        -1 & 5 & 6 & 7 \\
      \end{bmatrix}$$
      

In [81]:
def gen_max(n,m):
  #print("entre")
  #f n>=m:
  A = torch.rand(n,m); b = torch.randint(0,m,(n,))
  print(A); print(b)
  #cuando indezas con arange no te selecciona todo sino que funciona
  #como un contador interno. o sea, si pones A[:,:] te regresa toda la matriz A
  #pero si pones A[arange, arange] funcionara como 
  #contador que seleccionara la diagonal
  A[torch.arange(b.shape[0]), b] = -1
  
  return(A)

n = 6; m = 6
gen_max(n,m)



tensor([[6.1979e-01, 7.0634e-01, 1.6900e-01, 5.4990e-01, 9.7142e-01, 4.4149e-03],
        [3.1596e-01, 5.5254e-01, 1.9206e-01, 1.8683e-01, 4.1000e-01, 4.2057e-01],
        [6.9837e-01, 4.6353e-01, 7.8652e-02, 7.7124e-01, 7.6354e-05, 9.0258e-01],
        [5.0004e-01, 5.8152e-01, 3.7842e-01, 5.3923e-01, 3.0643e-01, 9.6395e-01],
        [5.1898e-01, 2.4334e-01, 4.9495e-01, 9.9774e-01, 3.0922e-01, 1.9330e-01],
        [8.8341e-01, 9.3300e-01, 2.7241e-01, 6.5700e-01, 6.0627e-01, 1.5415e-01]])
tensor([1, 0, 1, 0, 1, 0])


tensor([[ 6.1979e-01, -1.0000e+00,  1.6900e-01,  5.4990e-01,  9.7142e-01,
          4.4149e-03],
        [-1.0000e+00,  5.5254e-01,  1.9206e-01,  1.8683e-01,  4.1000e-01,
          4.2057e-01],
        [ 6.9837e-01, -1.0000e+00,  7.8652e-02,  7.7124e-01,  7.6354e-05,
          9.0258e-01],
        [-1.0000e+00,  5.8152e-01,  3.7842e-01,  5.3923e-01,  3.0643e-01,
          9.6395e-01],
        [ 5.1898e-01, -1.0000e+00,  4.9495e-01,  9.9774e-01,  3.0922e-01,
          1.9330e-01],
        [-1.0000e+00,  9.3300e-01,  2.7241e-01,  6.5700e-01,  6.0627e-01,
          1.5415e-01]])

In [32]:
m = 5
torch.randint(0,m,(m,))

tensor([4, 1, 4, 0, 4])

In [33]:
# estas son pruebas así que no prestes atencióón a esto, la funcióón gen_max es la que funciona
# solo que estaba teniendo problemas con n y m pero leyendo bien el problema lo entendíí 
# Dado que Carlos nos pidio que dejaramos los experimentos, por eso lo hice

#n = 3; m = 5
def gen_matrix(n,m):
  A = torch.rand(n,m)
  #A = torch.randint(0,10,(n,m))
  #A[n,torch.arange(b.shape[0])] = -1
  b = torch.arange(m)
  #print(b.shape)
  if n <= m:
    A[torch.arange(b.shape[0]), b] = -1
    return(A)
  elif m <= n:
    #A[torch.arange(b.shape[0]), b] = -1
    A[b,torch.arange(b.shape[0])] = -1
    return(A)
 #n = 3; m = 5 
A = torch.rand(6,3);b = torch.arange(3)
gen_matrix(6,3), A, b

(tensor([[-1.0000,  0.4213,  0.9639],
         [ 0.6980, -1.0000,  0.7379],
         [ 0.8960,  0.7924, -1.0000],
         [ 0.4633,  0.4073,  0.6844],
         [ 0.4599,  0.2999,  0.1535],
         [ 0.8547,  0.7504,  0.8206]]), tensor([[0.5109, 0.5347, 0.8920],
         [0.8237, 0.1743, 0.0202],
         [0.8009, 0.0441, 0.4389],
         [0.6005, 0.8294, 0.3218],
         [0.4031, 0.9875, 0.2767],
         [0.2024, 0.7467, 0.0479]]), tensor([0, 1, 2]))

#8. (**difícil**) Implementa, sin usar `@` ni matmul, multiplicación de matrices. Se vale usar `*`, `+`, `sum` y broadcasting.

In [94]:
n= 3; m=4

#A(3, 5)
#B(5,7)

A = torch.randint(1,11,(n,m)); B = torch.randint(1,11,(m,n))
#A = A[:,:,None]
#B = B[None,:,:]

A = A.unsqueeze(1)

result = A*B.T

#result = (A.T*B.T)
#tensor.sum(result)
#(3,5,1)
#(1,5,7)

#ATransformado*BTransformado.sum(dim==??)

torch.sum(result, -1), A@B

(tensor([[196,  54, 166],
         [146,  37, 120],
         [198,  87, 156]]), tensor([[[196,  54, 166]],
 
         [[146,  37, 120]],
 
         [[198,  87, 156]]]))

In [95]:
print(A,"\n\n",B)

tensor([[[9, 2, 4, 9]],

        [[1, 2, 7, 7]],

        [[2, 9, 8, 6]]]) 

 tensor([[ 8,  2,  7],
        [ 6,  7,  4],
        [10,  1,  8],
        [ 8,  2,  7]])


In [93]:
def notmul(n,m):
  A = torch.randint(1,11,(n,m)); B = torch.randint(1,11,(m,n))
  A = A.unsqueeze(1); B = B.T
  result = A*B
  return(torch.sum(result, -1))

n = 3; m=4
notmul(n,m)

tensor([[130,  56, 124],
        [148,  66, 152],
        [ 80,  37,  86]])